modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "loggerx"
version = "${version}"
displayName = "loggerx"
authors = "zly2006"
description = '''

'''
#logoFile = ""

[[dependencies.loggerx]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.loggerx]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"


[[mixins]]
config = "loggerx.mixins.json"
