modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/zly2006/logger-x/issues"
license = "All Rights Reserved"

[[mods]]
modId = "loggerx"
version = "${version}"
displayName = "loggerx"
authors = "zly2006"
description = '''

'''
#logoFile = ""

[[dependencies.loggerx]]
modId = "neoforge"
type = "required"
versionRange = "[1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.loggerx]]
modId = "minecraft"
type = "required"
versionRange = "[1.13,)"
ordering = "NONE"
side = "BOTH"
